# Generated by Django 4.1.4 on 2023-01-27 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cnab", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Song",
            new_name="Cnab",
        ),
    ]
